default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 222333
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ma7ally_development

test:
  <<: *default
  database: ma7ally_test

production:
  <<: *default
  database: ma7ally_production
  username: ma7ally
  password: <%= ENV['MA7ALLY_DATABASE_PASSWORD'] %>
